#!/bin/sh
#
#---Fetch the OneSearch academic tomcat logs from the 
#   archive server.
#
# Charles Roth, 2/28/2012
#------------------------------------------------------

if test "x$1" = "x"; then
   echo "Usage: fetchLogs mmdd"
   exit
fi

day=$1

echo "Fetching logs for $day..."
rm -rf logs$day
mkdir  logs$day
for server in `seq 101 140`; do
   echo $server
   scp vwprod@pqawstats101v.dc4.pqe:/mstarlog/pqwebapp$server/vwprod/app/prod/web/log/accL$day.log.gz \
       logs$day

   if test -f logs$day/accL$day.log.gz; then
      (cd logs$day; gunzip accL$day.log.gz)
   else
      scp vwprod@pqawstats101v.dc4.pqe:/mstarlog/pqwebapp$server/vwprod/app/prod/web/log/accL$day.log \
       logs$day
   fi

   mv logs$day/accL$day.log logs$day/$server-accL$day.log
done
